<header>
    <a class="navbar-brand" href="<?php echo $this->getUrl('admin/user/dashboard') ?>">Furni<span>.</span></a>
    <nav>
        <ul>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Messages</a></li>
            <li><a href="#">Notifications</a></li>
            <li>
                <a href="<?php echo $this->getUrl('admin/user/logout') ?>"><img
                        src="<?php echo Mage::getImagePath('images/logout_dark.png') ?>"></a>
            </li>
        </ul>
    </nav>
</header>