<div class="sidebar  navbar-dark">

	<a class="navbar-brand" href="<?php echo $this->getUrl('admin/user/dashboard') ?>"
		style="font-size: xx-large">Furni<span>.</span></a>
	<br>
	<br>
	<ul>
		<li><a href="<?php echo $this->getUrl('admin/user/dashboard') ?>">Home</a></li>
		<li><a href="<?php echo $this->getUrl('admin/catalog_product/form') ?>">Product Form</a></li>
		<li><a href="<?php echo $this->getUrl('admin/catalog_product/list') ?>">Product List</a></li>
		<li><a href="<?php echo $this->getUrl('admin/catalog_category/form') ?>">Category Form</a></li>
		<li><a href="<?php echo $this->getUrl('admin/catalog_category/list') ?>">Category List</a></li>
		<li><a href="<?php echo $this->getUrl('admin/import_import/index') ?>">Import CSV File Form</a></li>
		<li><a href="<?php echo $this->getUrl('admin/banner/form') ?>">Banner Form</a></li>
		<li><a href="<?php echo $this->getUrl('admin/banner/list') ?>">Banner List</a></li>
		<li><a href="<?php echo $this->getUrl('admin/order_history/list') ?>">Order List</a></li>
		<li><a href="#">Settings</a></li>
	</ul>
</div>