<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <?php echo ($this->getChildHtml('head')); ?>
</head>

<body>
    <div class="dashboard">
        <?php echo ($this->getChildHtml('admin_sidebar')); ?>
        <div class="content-1">
                <?php echo ($this->getChildHtml('admin_header')); ?>
            <div>
                <?php echo ($this->getChildHtml('content')); ?>
            </div>
        </div>
    </div>
</body>

</html>