<div class="untree_co-section">
    <div class="container" style="width: 800px;">
        <div class="row ">
            <div>
                <h2 class="h3 mb-3 text-black">File Store in Media folder</h2>
                <div class="p-3 p-lg-5 border bg-white">
                    <form action="<?php echo $this->getUrl('Admin/Import_Import/save'); ?>" method="post"
                        enctype="multipart/form-data">
                        <div class="form-group row">

                            <div class="col-md-12">
                                <label for="file" class="text-black">Import CSV file<span
                                        class="text-danger">*</span></label>
                                <input type="file" name="file" class="form-control" required>
                            </div>

                        </div>
                        <br>
                        <div class="form-group">
                            <input class="btn btn-black btn-lg py-3 btn-block" type="submit" name="submit"
                                value="Upload CSV File">
                        </div>
                    </form>
                    <!-- <div class="form-group">
                        <input class="btn btn-black btn-lg py-3 btn-block" type="submit" name="submit"
                            value="Read CSV File">
                    </div> -->
                </div>

            </div>

        </div>

    </div>
</div>