<div class="untree_co-section">
    <div class="container" style="width: 800px;">
        <form action="<?php echo $this->getUrl('customer/account/login'); ?>" method="post">
            <div class="row ">
                <div>
                    <h2 class="h3 mb-3 text-black">Login</h2>
                    <div class="p-3 p-lg-5 border bg-white">
                        <div class="form-group row">
                            <div class="col-md-12">
                                <label for="customer_email" class="text-black">E-mail<span
                                        class="text-danger">*</span></label>
                                <input type="email" class="form-control" id="customer_email" name="customer[customer_email]"
                                    placeholder="Enter E-mail" value="" required>
                            </div>
                            <div class="col-md-12">
                                <label for="password" class="text-black">Password<span
                                        class="text-danger">*</span></label>
                                <input type="password" class="form-control" id="password" name="customer[password]"
                                    placeholder="Enter Password" value="" required>
                            </div>
                        </div>
                        <div style="margin-top: 30px;">
                            <div class="form-group">
                                <input class="btn btn-black btn-lg py-3 btn-block" type="submit" name="Submit"
                                    value="Login">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>