<div class="untree_co-section">
    <div class="container" style="width: 800px;">
        <form action="<?php echo $this->getUrl('admin/banner/save') ?>" method="post">
            <div class="row">
                <div>
                    <h2 class="h3 mb-3 text-black">Banner Information</h2>
                    <div class="p-3 p-lg-5 border bg-white">
                        <div class="form-group row">
                            <input type="hidden" class="form-control" id="banner_id" name="banner[banner_id]"
                                value="<?php echo $this->getBanner()->getBannerId(); ?>" required>

                            <div class="col-md-6">
                                <label for="banner_image" class="text-black">Image<span
                                        class="text-danger">*</span></label>
                                <input type="file" class="form-control" id="banner_image" name="banner[banner_image]"
                                    value="<?php echo $this->getBanner()->getBannerImage(); ?>" required>
                            </div>

                            <div class="col-md-6">
                                <label for="status" class="text-black">Status<span
                                        class="text-danger">*</span></label>
                                <select id="status" class="form-control" name="banner[status]">
                                    <option value="" hidden>Select Status</option>
                                    <option <?php echo (($this->getBanner()->getStatus() == "Disabled") ? 'selected' : '') ?>
                                        value="0">Disabled</option>
                                    <option <?php echo (($this->getBanner()->getStatus() == "Enabled") ? 'selected' : '') ?> value="1">
                                        Enabled</option>
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label for="show_on" class="text-black">Show On<span
                                        class="text-danger">*</span></label>
                                <input type="text" class="form-control" id="show_on" name="banner[show_on]"
                                    placeholder="Enter Show On" value="<?php echo $this->getBanner()->getShowOn(); ?>" required>
                            </div>
                            <div style="margin-top: 30px;">
                                <div class="form-group">
                                    <input class="btn btn-black btn-lg py-3 btn-block" type="submit" name="submit"
                                        value="Submit">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>